[package]
org = "ballerinax"
name = "file_upload_signed_url"
version = "0.1.0"
distribution = "2201.12.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "hubspot.files"
version = "0.1.0"
repository = "local"
